# Generated by Django 4.1.5 on 2023-04-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='about',
        ),
        migrations.AddField(
            model_name='appuser',
            name='description',
            field=models.TextField(blank=True, default='', max_length=600, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='major',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Major(s)/minor(s)'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='year',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Year'),
        ),
        migrations.DeleteModel(
            name='TutorProfile',
        ),
    ]
