# Generated by Django 4.1.7 on 2023-04-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0002_tutorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='courses',
            field=models.ManyToManyField(to='tutorme.courseastext'),
        ),
    ]
