# Generated by Django 4.1.7 on 2023-04-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='tutor',
        ),
    ]
