# Generated by Django 4.1.7 on 2023-04-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_builder', '0002_remove_events_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='event_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
